name: Feature Request
description: Suggest a new feature or enhancement for Armbian Imager
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe your idea in detail so we can evaluate and potentially implement it.

  - type: checkboxes
    id: existing-request
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting
      options:
        - label: I have searched the existing issues and this feature has not been requested before
          required: true

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which area of the application does this feature relate to?
      options:
        - User Interface / UX
        - Download functionality
        - Flash/Write functionality
        - Device detection
        - Image selection / Board support
        - Custom image handling
        - Verification / Validation
        - Platform support (Windows/macOS/Linux)
        - Localization / Translations
        - Performance
        - Accessibility
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe the problem you're trying to solve.
      placeholder: "I'm always frustrated when... / Currently there's no way to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: "I would like to be able to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or workarounds you've considered
      placeholder: "I've tried... but it doesn't work because..."

  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature to you?
      options:
        - Nice to have
        - Would significantly improve my workflow
        - Critical for my use case
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe a specific scenario where this feature would be useful
      placeholder: "When I'm flashing multiple boards, I need to..."

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / Examples
      description: If applicable, add mockups, sketches, or examples from other applications

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here
