import { load } from '@tauri-apps/plugin-store';

const AUTOCONFIG_STORE = '.autoconfig.dat';
let storeInstance: Awaited<ReturnType<typeof load>> | null = null;

async function getStore() {
  if (!storeInstance) {
    storeInstance = await load(AUTOCONFIG_STORE, { autoSave: true, defaults: {} });
  }
  return storeInstance;
}

// Keys
const K_ENABLE = 'autoconfig.enable';
const K_WIFI_ENABLED = 'autoconfig.wifi.enabled';
const K_WIFI_SSID = 'autoconfig.wifi.ssid';
const K_WIFI_KEY = 'autoconfig.wifi.key';
const K_WIFI_CC = 'autoconfig.wifi.countrycode';
const K_USER_NAME = 'autoconfig.user.name';
const K_USER_PASS = 'autoconfig.user.password';
const K_USER_KEY = 'autoconfig.user.key';
const K_USER_SHELL = 'autoconfig.user.shell';
const K_USER_REALNAME = 'autoconfig.user.realname';
const K_ROOT_PASS = 'autoconfig.root.password';
const K_ROOT_KEY = 'autoconfig.root.key';
const K_LOCALE = 'autoconfig.system.locale';
const K_TIMEZONE = 'autoconfig.system.timezone';
const K_STATIC_IP_ENABLED = 'autoconfig.network.static.enabled';
const K_STATIC_IP = 'autoconfig.network.static.ip';
const K_STATIC_MASK = 'autoconfig.network.static.mask';
const K_STATIC_GATEWAY = 'autoconfig.network.static.gateway';
const K_STATIC_DNS = 'autoconfig.network.static.dns';

// Utility for getting strings/booleans
async function getBool(key: string, def = false): Promise<boolean> {
  const store = await getStore();
  const val = await store.get<boolean>(key);
  return val ?? def;
}
async function setBool(key: string, val: boolean) {
  const store = await getStore();
  await store.set(key, val);
  await store.save();
}
async function getString(key: string, def = ''): Promise<string> {
  const store = await getStore();
  const val = await store.get<string>(key);
  return val ?? def;
}
async function setString(key: string, val: string) {
  const store = await getStore();
  await store.set(key, val);
  await store.save();
}

export const getAutoconfigEnabled = () => getBool(K_ENABLE, false);
export const setAutoconfigEnabled = (v: boolean) => setBool(K_ENABLE, v);

export const getWifiEnabled = () => getBool(K_WIFI_ENABLED, false);
export const setWifiEnabled = (v: boolean) => setBool(K_WIFI_ENABLED, v);

export const getWifiSsid = () => getString(K_WIFI_SSID, '');
export const setWifiSsid = (v: string) => setString(K_WIFI_SSID, v);

export const getWifiKey = () => getString(K_WIFI_KEY, '');
export const setWifiKey = (v: string) => setString(K_WIFI_KEY, v);

export const getWifiCountryCode = () => getString(K_WIFI_CC, 'US');
export const setWifiCountryCode = (v: string) => setString(K_WIFI_CC, v);

export const getUserName = () => getString(K_USER_NAME, 'armbian');
export const setUserName = (v: string) => setString(K_USER_NAME, v);

export const getUserPassword = () => getString(K_USER_PASS, '');
export const setUserPassword = (v: string) => setString(K_USER_PASS, v);

export const getUserKey = () => getString(K_USER_KEY, '');
export const setUserKey = (v: string) => setString(K_USER_KEY, v);

export const getUserShell = () => getString(K_USER_SHELL, 'bash');
export const setUserShell = (v: string) => setString(K_USER_SHELL, v);

export const getUserRealName = () => getString(K_USER_REALNAME, 'Armbian User');
export const setUserRealName = (v: string) => setString(K_USER_REALNAME, v);

export const getRootPassword = () => getString(K_ROOT_PASS, '');
export const setRootPassword = (v: string) => setString(K_ROOT_PASS, v);

export const getRootKey = () => getString(K_ROOT_KEY, '');
export const setRootKey = (v: string) => setString(K_ROOT_KEY, v);

export const getLocale = () => getString(K_LOCALE, 'en_US.UTF-8');
export const setLocale = (v: string) => setString(K_LOCALE, v);

export const getTimezone = () => getString(K_TIMEZONE, 'America/Chicago');
export const setTimezone = (v: string) => setString(K_TIMEZONE, v);

export const getStaticIpEnabled = () => getBool(K_STATIC_IP_ENABLED, false);
export const setStaticIpEnabled = (v: boolean) => setBool(K_STATIC_IP_ENABLED, v);

export const getStaticIp = () => getString(K_STATIC_IP, '');
export const setStaticIp = (v: string) => setString(K_STATIC_IP, v);

export const getStaticMask = () => getString(K_STATIC_MASK, '255.255.255.0');
export const setStaticMask = (v: string) => setString(K_STATIC_MASK, v);

export const getStaticGateway = () => getString(K_STATIC_GATEWAY, '');
export const setStaticGateway = (v: string) => setString(K_STATIC_GATEWAY, v);

export const getStaticDns = () => getString(K_STATIC_DNS, '8.8.8.8 8.8.4.4');
export const setStaticDns = (v: string) => setString(K_STATIC_DNS, v);

export async function generateAutoconfigPayload(): Promise<string> {
  if (!(await getAutoconfigEnabled())) return '';

  const lines: string[] = [];
  lines.push('#/root/.not_logged_in_yet Generated by Armbian Imager');
  
  if (await getWifiEnabled()) {
    lines.push('PRESET_NET_CHANGE_DEFAULTS="1"');
    lines.push('PRESET_NET_ETHERNET_ENABLED="1"'); // Required per Armbian docs default
    lines.push('PRESET_NET_WIFI_ENABLED="1"');
    lines.push(`PRESET_NET_WIFI_SSID="${await getWifiSsid()}"`);
    lines.push(`PRESET_NET_WIFI_KEY="${await getWifiKey()}"`);
    lines.push(`PRESET_NET_WIFI_COUNTRYCODE="${await getWifiCountryCode()}"`);
    lines.push('PRESET_CONNECT_WIRELESS="y"');
  }

  if (await getStaticIpEnabled()) {
    lines.push('PRESET_NET_CHANGE_DEFAULTS="1"');
    lines.push('PRESET_NET_USE_STATIC="1"');
    lines.push(`PRESET_NET_STATIC_IP="${await getStaticIp()}"`);
    lines.push(`PRESET_NET_STATIC_MASK="${await getStaticMask()}"`);
    lines.push(`PRESET_NET_STATIC_GATEWAY="${await getStaticGateway()}"`);
    lines.push(`PRESET_NET_STATIC_DNS="${await getStaticDns()}"`);
  }

  const locale = await getLocale();
  if (locale) {
    lines.push('SET_LANG_BASED_ON_LOCATION="n"');
    lines.push(`PRESET_LOCALE="${locale}"`);
  }

  const tz = await getTimezone();
  if (tz) lines.push(`PRESET_TIMEZONE="${tz}"`);

  const rootpass = await getRootPassword();
  if (rootpass) lines.push(`PRESET_ROOT_PASSWORD="${rootpass}"`);

  const rootkey = await getRootKey();
  if (rootkey) lines.push(`PRESET_ROOT_KEY="${rootkey.trim()}"`);

  const user = await getUserName();
  const userpass = await getUserPassword();
  if (user && userpass) {
    lines.push(`PRESET_USER_NAME="${user}"`);
    lines.push(`PRESET_USER_PASSWORD="${userpass}"`);
    
    const userkey = await getUserKey();
    if (userkey) lines.push(`PRESET_USER_KEY="${userkey.trim()}"`);
    
    const userreal = await getUserRealName();
    if (userreal) lines.push(`PRESET_DEFAULT_REALNAME="${userreal}"`);
    
    const shell = await getUserShell();
    if (shell) lines.push(`PRESET_USER_SHELL="${shell}"`);
  }

  return lines.join('\n');
}
